### ISSUE TITLE
upgrade to angular 4

### ISSUE THREAD

**Issue by rustan-id** [PacktPublishing/Essential-Angular#1]
$ ng serve
Unable to find "@angular/cli" in devDependencies.

The package "angular-cli" has been deprecated and renamed to "@angular/cli".

Please take the following steps to avoid issues:
"npm uninstall --save-dev angular-cli"
"npm install --save-dev @angular/cli@latest" 

The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

$ npm uninstall --save-dev angular-cli
removed 533 packages in 23.611s
$ npm install --save-dev @angular/cli@latest
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /home/gmaimunah/Documents/Angular/Essential Angularr Victor Savkin/Essential-Angular/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/gmaimunah/.npm/node-sass/4.5.3/linux-x64-48_binding.node

> node-sass@4.5.3 postinstall /home/gmaimunah/Documents/Angular/Essential Angularr Victor Savkin/Essential-Angular/node_modules/node-sass
> node scripts/build.js

Binary found at /home/gmaimunah/Documents/Angular/Essential Angularr Victor Savkin/Essential-Angular/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
+ @angular/cli@1.1.1
added 453 packages in 76.246s

$ ng serve
Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
[gmaimunah@ghina-id Essential-Angular]$ 

How to do that?

**Comment by rustan-id** [comment]
this is my angular-cli.json when it was updated.

{
  "project": {
    "version": "1.0.0-beta.24",
    "name": "essentials-angular-app"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
	"environmentSource": "environments/environment.ts",
	"environments": {
	  "dev": "environments/environment.ts",
	  "prod": "environments/environment.prod.ts"
	}
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

And then get this Error:

$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 3d791c5a59c72361e58d                                                               
Time: 32883ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 22.1 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 10.5 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.44 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/watch-button/watch-button.component.ts
Module not found: Error: Can't resolve './watch-button.component.css' in '/home/gmaimunah/Documents/Angular/Essential Angularr Victor Savkin/Essential-Angular/src/app/watch-button'
 @ ./src/app/watch-button/watch-button.component.ts 33:17-56
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/rate-button/rate-button.component.ts
Module not found: Error: Can't resolve './rate-button.component.css' in '/home/gmaimunah/Documents/Angular/Essential Angularr Victor Savkin/Essential-Angular/src/app/rate-button'
 @ ./src/app/rate-button/rate-button.component.ts 36:17-55
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

**Comment by rustan-id** [comment]
File './watch-button.component.css' and './rate-button.component.css' was missing or from the beginning there is no css file in folder rate-button and watch-button ?

**Comment by rustan-id** [comment]
File './watch-button.component.css' and './rate-button.component.css' was missing or from the beginning there is no css file in folder rate-button and watch-button ?

**Comment by ManikandanKurup-Packt** [comment]
Please reopen the issue if this error still exists. Thanks!
